[package]
name = "bad-apple"
version = "0.4.0"
edition = "2024"
description = "A terminal-based player for videos."
readme = "README.md"
homepage = "https://github.com/leetdavid/bad-apple-rust"
repository = "https://github.com/leetdavid/bad-apple-rust"
license = "MIT"

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
dirs = "5"
ratatui = "0.29"
rodio = "0.19.0"
unicode-width = "0.2.0"
